name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "spotifymoody"
          heroku_email: "hirdman.alex@icloud.com"
          usedocker: true
          docker_build_args: |
            NODE_ENV
            SECRET_KEY
        # env:
        #   NODE_ENV: production
        #   SECRET_KEY: ${{ secrets.MY_SECRET_KEY }}