name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/browsers:node16.16.0-chrome107-ff107-edge
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Install Firebase Emulator Suite 🔥
        run: npm install --location=global firebase-tools

      - name: Cypress 🧪
        uses: cypress-io/github-action@v5
        env:
          CYPRESS_USERMAIL: ${{ secrets.CYPRESS_USERMAIL }}
          CYPRESS_PASSWORD: '${{ secrets.CYPRESS_PASSWORD }}'
        with:
          browser: chrome
          start: |
            npm run build
            npm run cypress:ci
          wait-on: 'http://localhost:3000'
